name: Apply - Test
on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  apply:
    name: Apply
    uses: ./.github/workflows/apply.yml
    with:
      environment: test
      aws-account-id: 869935096717
      maintenance-mode-on: ${{ vars.MAINTENANCE_MODE_ON_TEST == 'true'}}
    secrets: inherit