name: Apply - Integration
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply:
    name: Apply
    uses: ./.github/workflows/apply.yml
    with:
      environment: integration
      aws-account-id: 794038239680
      maintenance-mode-on: ${{ vars.MAINTENANCE_MODE_ON_INTEGRATION == 'true'}}
    secrets: inherit
