name: Apply - Test
on:
  push:
    branches:
      - test

jobs:
  apply:
    name: Apply
    uses: ./.github/workflows/apply.yml
    with:
      environment: test
      aws-account-id: 869935096717
      maintenance-mode-on: false
    secrets: inherit