name: Apply - Integration
on:
  push:
    branches:
      - main
      - feat/prsd-981-update-ssm-patch-manager

jobs:
  apply:
    name: Apply
    uses: ./.github/workflows/apply.yml
    with:
      environment: integration
      aws-account-id: 794038239680
    secrets: inherit
