name: Check and Plan - Test
on: pull_request

jobs:
  check-and-plan:
    name: Check and Plan
    uses: ./.github/workflows/check-and-plan.yml
    with:
      environment: test
      aws-account-id: 869935096717
