name: Check and Plan
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws-account-id:
        required: true
        type: string

jobs:
  validate-target-environment:
    name: Validate Target Environment
    uses: ./.github/workflows/validate-target-environment.yml
    with:
      environment: ${{ inputs.environment }}

  format:
    name: tf format
    needs: validate-target-environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1

      - name: Check formatting of all terraform files
        run: terraform fmt -check -recursive

  validate:
    name: tf validate
    needs: validate-target-environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1

      - name: Terraform init ${{ inputs.environment }} folder
        working-directory: terraform/${{ inputs.environment }}
        run: terraform init -backend=false

      - name: Terraform validate ${{ inputs.environment }} folder
        working-directory: terraform/${{ inputs.environment }}
        run: terraform validate

      - name: Terraform init ${{ inputs.environment }} backend folder
        working-directory: terraform/${{ inputs.environment }}/backend
        run: terraform init -backend=false

      - name: Terraform validate ${{ inputs.environment }} backend folder
        working-directory: terraform/${{ inputs.environment }}/backend
        run: terraform validate

  tflint:
    name: tflint
    needs: validate-target-environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1

      - name: Cache plugin directory for tflint
        uses: actions/cache@v3
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Set up tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.54.0

      - name: Init tflint
        run: tflint --init

      - name: Run tflint
        run: tflint --recursive --config "$(pwd)/.tflint.hcl" --format=compact --color

  tfsec:
    name: tfsec
    needs: validate-target-environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: terraform/
          version: v1.28.11

  plan:
    name: ${{ inputs.environment }} terraform plan
    needs: validate-target-environment
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: "eu-west-2"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/github-actions-terraform-ci-plan-read-only
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.1

      - name: Terraform init
        run: terraform init -input=false
        working-directory: terraform/${{ inputs.environment }}

      - name: Terraform validate
        run: terraform validate
        working-directory: terraform/${{ inputs.environment }}

      - name: Terraform plan
        run: terraform plan -input=false -refresh=false -lock=false
        working-directory: terraform/${{ inputs.environment }}