name: Deploy - Production
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      aws-account-id: 879161327637