name: Deploy - NFT
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      environment: nft
      aws-account-id: 448120078528