name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        description: "The name of the environment to deploy to"
        type: string
        required: true
      account_id:
        description: "The id of the AWS account to deploy to"
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  validate-target-environment:
    name: Validate Target Environment
    uses: ./.github/workflows/validate-target-environment.yml
    with:
      environment: ${{ inputs.environment }}

  retrieve-image:
    name: Retrieve Latest ECR Image
    needs: validate-target-environment
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.retrieve-image.outputs.image_tag }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.account_id }}:role/${{ inputs.environment }}-ecr-describe-images
          aws-region: eu-west-2

      - name: Retrieve Latest Image Tag
        id: retrieve-image
        run: |
          IMAGE_TAG=$(aws ecr describe-images --repository-name ${{ inputs.environment }}-webapp --query 'sort_by(imageDetails, &imagePushedAt)[-1].imageTags[0]' --output text)
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  update-task-definition:
    name: Update ECS task definition
    needs: retrieve-image
    uses: ./.github/workflows/update-task-definition.yml
    with:
      environment_name: ${{ inputs.environment }}
      account_id: ${{ inputs.account_id }}
      image_name: ${{ needs.retrieve-image.outputs.image_tag }}

  update-ecs-service:
    name: Update ECS service
    needs: update-task-definition
    uses: ./.github/workflows/update-ecs-service.yml
    with:
      environment_name: ${{ inputs.environment }}
      account_id: ${{ inputs.account_id }}