name: Deploy - Integration
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    with:
      environment: integration
      aws-account-id: 794038239680