name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        description: "The name of the environment to deploy to"
        type: string
        required: true
      aws-account-id:
        description: "The id of the AWS account to deploy to"
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  validate-target-environment:
    name: Validate target environment
    uses: ./.github/workflows/validate-target-environment.yml
    with:
      environment: ${{ inputs.environment }}

  refresh-task-definitions:
    name: Refresh task definitions
    needs: validate-target-environment
    uses: ./.github/workflows/refresh-task-definitions.yml
    with:
      environment: ${{ inputs.environment }}
      aws-account-id: ${{ inputs.aws-account-id }}

  update-ecs-service:
    name: Update ECS service
    needs: refresh-task-definitions
    uses: ./.github/workflows/update-ecs-service.yml
    with:
      environment: ${{ inputs.environment }}
      aws-account-id: ${{ inputs.aws-account-id }}